name: Test clone repo

on:
  push:
    branches:
      - master

jobs:
  my_ci_part:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Configure repo
        uses: actions/checkout@v2
      - run: find . -type f -name "*.*" -print0 | xargs -0 sed -i 's/dtuchs/ilya911602/g'
      - 
        name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - 
        name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.TOKEN_DOCKER }}
      - run: bash docker-compose-ci-dev.sh push
  
  my_cd_part:
    runs-on: ubuntu-latest
    needs: [my_ci_part]
    steps:
      - 
        name: Configure repo
        uses: actions/checkout@v2
      - run: find . -type f -name "*.*" -print0 | xargs -0 sed -i 's/dtuchs/ilya911602/g'
      -
        name: Copy to server
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbook.yml
          key: ${{secrets.SSH_PRIVATE_KEY_TEST}}
          directory: ansible_deploy
          options: --inventory hosts